# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'petMatch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for petMatch
  pod 'Parse'
  pod 'AlamofireImage'

  target 'petMatchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'petMatchUITests' do
    # Pods for testing
  end

end
